import CPU from "./CPU";
interface opcodeStruct {
  name: string;
  operation: () => number;
  addrmode: () => number;
  cycles: number;
}

export class Opcode {
  private lookup: opcodeStruct[];
  constructor(cpu: CPU) {
    this.lookup = [
      { name: "BRK", operation: cpu.BRK, addrmode: cpu.IMM, cycles: 7 },
      { name: "ORA", operation: cpu.ORA, addrmode: cpu.IZX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 3 },
      { name: "ORA", operation: cpu.ORA, addrmode: cpu.ZP0, cycles: 3 },
      { name: "ASL", operation: cpu.ASL, addrmode: cpu.ZP0, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },
      { name: "PHP", operation: cpu.PHP, addrmode: cpu.IMP, cycles: 3 },
      { name: "ORA", operation: cpu.ORA, addrmode: cpu.IMM, cycles: 2 },
      { name: "ASL", operation: cpu.ASL, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 4 },
      { name: "ORA", operation: cpu.ORA, addrmode: cpu.ABS, cycles: 4 },
      { name: "ASL", operation: cpu.ASL, addrmode: cpu.ABS, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },

      { name: "BPL", operation: cpu.BPL, addrmode: cpu.REL, cycles: 2 },
      { name: "ORA", operation: cpu.ORA, addrmode: cpu.IZY, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "ORA", operation: cpu.ORA, addrmode: cpu.ZPX, cycles: 4 },
      { name: "ASL", operation: cpu.ASL, addrmode: cpu.ZPX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },
      { name: "CLC", operation: cpu.CLC, addrmode: cpu.IMP, cycles: 2 },
      { name: "ORA", operation: cpu.ORA, addrmode: cpu.ABY, cycles: 4 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "ORA", operation: cpu.ORA, addrmode: cpu.ABX, cycles: 4 },
      { name: "ASL", operation: cpu.ASL, addrmode: cpu.ABX, cycles: 7 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },

      { name: "JSR", operation: cpu.JSR, addrmode: cpu.ABS, cycles: 6 },
      { name: "AND", operation: cpu.AND, addrmode: cpu.IZX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "BIT", operation: cpu.BIT, addrmode: cpu.ZP0, cycles: 3 },
      { name: "AND", operation: cpu.AND, addrmode: cpu.ZP0, cycles: 3 },
      { name: "ROL", operation: cpu.ROL, addrmode: cpu.ZP0, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },
      { name: "PLP", operation: cpu.PLP, addrmode: cpu.IMP, cycles: 4 },
      { name: "AND", operation: cpu.AND, addrmode: cpu.IMM, cycles: 2 },
      { name: "ROL", operation: cpu.ROL, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "BIT", operation: cpu.BIT, addrmode: cpu.ABS, cycles: 4 },
      { name: "AND", operation: cpu.AND, addrmode: cpu.ABS, cycles: 4 },
      { name: "ROL", operation: cpu.ROL, addrmode: cpu.ABS, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },

      { name: "BMI", operation: cpu.BMI, addrmode: cpu.REL, cycles: 2 },
      { name: "AND", operation: cpu.AND, addrmode: cpu.IZY, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "AND", operation: cpu.AND, addrmode: cpu.ZPX, cycles: 4 },
      { name: "ROL", operation: cpu.ROL, addrmode: cpu.ZPX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },
      { name: "SEC", operation: cpu.SEC, addrmode: cpu.IMP, cycles: 2 },
      { name: "AND", operation: cpu.AND, addrmode: cpu.ABY, cycles: 4 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "AND", operation: cpu.AND, addrmode: cpu.ABX, cycles: 4 },
      { name: "ROL", operation: cpu.ROL, addrmode: cpu.ABX, cycles: 7 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },

      { name: "RTI", operation: cpu.RTI, addrmode: cpu.IMP, cycles: 6 },
      { name: "EOR", operation: cpu.EOR, addrmode: cpu.IZX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 3 },
      { name: "EOR", operation: cpu.EOR, addrmode: cpu.ZP0, cycles: 3 },
      { name: "LSR", operation: cpu.LSR, addrmode: cpu.ZP0, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },
      { name: "PHA", operation: cpu.PHA, addrmode: cpu.IMP, cycles: 3 },
      { name: "EOR", operation: cpu.EOR, addrmode: cpu.IMM, cycles: 2 },
      { name: "LSR", operation: cpu.LSR, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "JMP", operation: cpu.JMP, addrmode: cpu.ABS, cycles: 3 },
      { name: "EOR", operation: cpu.EOR, addrmode: cpu.ABS, cycles: 4 },
      { name: "LSR", operation: cpu.LSR, addrmode: cpu.ABS, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },

      { name: "BVC", operation: cpu.BVC, addrmode: cpu.REL, cycles: 2 },
      { name: "EOR", operation: cpu.EOR, addrmode: cpu.IZY, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "EOR", operation: cpu.EOR, addrmode: cpu.ZPX, cycles: 4 },
      { name: "LSR", operation: cpu.LSR, addrmode: cpu.ZPX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },
      { name: "CLI", operation: cpu.CLI, addrmode: cpu.IMP, cycles: 2 },
      { name: "EOR", operation: cpu.EOR, addrmode: cpu.ABY, cycles: 4 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "EOR", operation: cpu.EOR, addrmode: cpu.ABX, cycles: 4 },
      { name: "LSR", operation: cpu.LSR, addrmode: cpu.ABX, cycles: 7 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },

      { name: "RTS", operation: cpu.RTS, addrmode: cpu.IMP, cycles: 6 },
      { name: "ADC", operation: cpu.ADC, addrmode: cpu.IZX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 3 },
      { name: "ADC", operation: cpu.ADC, addrmode: cpu.ZP0, cycles: 3 },
      { name: "ROR", operation: cpu.ROR, addrmode: cpu.ZP0, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },
      { name: "PLA", operation: cpu.PLA, addrmode: cpu.IMP, cycles: 4 },
      { name: "ADC", operation: cpu.ADC, addrmode: cpu.IMM, cycles: 2 },
      { name: "ROR", operation: cpu.ROR, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "JMP", operation: cpu.JMP, addrmode: cpu.IND, cycles: 5 },
      { name: "ADC", operation: cpu.ADC, addrmode: cpu.ABS, cycles: 4 },
      { name: "ROR", operation: cpu.ROR, addrmode: cpu.ABS, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },

      { name: "BVS", operation: cpu.BVS, addrmode: cpu.REL, cycles: 2 },
      { name: "ADC", operation: cpu.ADC, addrmode: cpu.IZY, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "ADC", operation: cpu.ADC, addrmode: cpu.ZPX, cycles: 4 },
      { name: "ROR", operation: cpu.ROR, addrmode: cpu.ZPX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },
      { name: "SEI", operation: cpu.SEI, addrmode: cpu.IMP, cycles: 2 },
      { name: "ADC", operation: cpu.ADC, addrmode: cpu.ABY, cycles: 4 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "ADC", operation: cpu.ADC, addrmode: cpu.ABX, cycles: 4 },
      { name: "ROR", operation: cpu.ROR, addrmode: cpu.ABX, cycles: 7 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },

      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "STA", operation: cpu.STA, addrmode: cpu.IZX, cycles: 6 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },
      { name: "STY", operation: cpu.STY, addrmode: cpu.ZP0, cycles: 3 },
      { name: "STA", operation: cpu.STA, addrmode: cpu.ZP0, cycles: 3 },
      { name: "STX", operation: cpu.STX, addrmode: cpu.ZP0, cycles: 3 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 3 },
      { name: "DEY", operation: cpu.DEY, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "TXA", operation: cpu.TXA, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "STY", operation: cpu.STY, addrmode: cpu.ABS, cycles: 4 },
      { name: "STA", operation: cpu.STA, addrmode: cpu.ABS, cycles: 4 },
      { name: "STX", operation: cpu.STX, addrmode: cpu.ABS, cycles: 4 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 4 },

      { name: "BCC", operation: cpu.BCC, addrmode: cpu.REL, cycles: 2 },
      { name: "STA", operation: cpu.STA, addrmode: cpu.IZY, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },
      { name: "STY", operation: cpu.STY, addrmode: cpu.ZPX, cycles: 4 },
      { name: "STA", operation: cpu.STA, addrmode: cpu.ZPX, cycles: 4 },
      { name: "STX", operation: cpu.STX, addrmode: cpu.ZPY, cycles: 4 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 4 },
      { name: "TYA", operation: cpu.TYA, addrmode: cpu.IMP, cycles: 2 },
      { name: "STA", operation: cpu.STA, addrmode: cpu.ABY, cycles: 5 },
      { name: "TXS", operation: cpu.TXS, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 5 },
      { name: "STA", operation: cpu.STA, addrmode: cpu.ABX, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },

      { name: "LDY", operation: cpu.LDY, addrmode: cpu.IMM, cycles: 2 },
      { name: "LDA", operation: cpu.LDA, addrmode: cpu.IZX, cycles: 6 },
      { name: "LDX", operation: cpu.LDX, addrmode: cpu.IMM, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },
      { name: "LDY", operation: cpu.LDY, addrmode: cpu.ZP0, cycles: 3 },
      { name: "LDA", operation: cpu.LDA, addrmode: cpu.ZP0, cycles: 3 },
      { name: "LDX", operation: cpu.LDX, addrmode: cpu.ZP0, cycles: 3 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 3 },
      { name: "TAY", operation: cpu.TAY, addrmode: cpu.IMP, cycles: 2 },
      { name: "LDA", operation: cpu.LDA, addrmode: cpu.IMM, cycles: 2 },
      { name: "TAX", operation: cpu.TAX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "LDY", operation: cpu.LDY, addrmode: cpu.ABS, cycles: 4 },
      { name: "LDA", operation: cpu.LDA, addrmode: cpu.ABS, cycles: 4 },
      { name: "LDX", operation: cpu.LDX, addrmode: cpu.ABS, cycles: 4 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 4 },

      { name: "BCS", operation: cpu.BCS, addrmode: cpu.REL, cycles: 2 },
      { name: "LDA", operation: cpu.LDA, addrmode: cpu.IZY, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },
      { name: "LDY", operation: cpu.LDY, addrmode: cpu.ZPX, cycles: 4 },
      { name: "LDA", operation: cpu.LDA, addrmode: cpu.ZPX, cycles: 4 },
      { name: "LDX", operation: cpu.LDX, addrmode: cpu.ZPY, cycles: 4 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 4 },
      { name: "CLV", operation: cpu.CLV, addrmode: cpu.IMP, cycles: 2 },
      { name: "LDA", operation: cpu.LDA, addrmode: cpu.ABY, cycles: 4 },
      { name: "TSX", operation: cpu.TSX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 4 },
      { name: "LDY", operation: cpu.LDY, addrmode: cpu.ABX, cycles: 4 },
      { name: "LDA", operation: cpu.LDA, addrmode: cpu.ABX, cycles: 4 },
      { name: "LDX", operation: cpu.LDX, addrmode: cpu.ABY, cycles: 4 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 4 },

      { name: "CPY", operation: cpu.CPY, addrmode: cpu.IMM, cycles: 2 },
      { name: "CMP", operation: cpu.CMP, addrmode: cpu.IZX, cycles: 6 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "CPY", operation: cpu.CPY, addrmode: cpu.ZP0, cycles: 3 },
      { name: "CMP", operation: cpu.CMP, addrmode: cpu.ZP0, cycles: 3 },
      { name: "DEC", operation: cpu.DEC, addrmode: cpu.ZP0, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },
      { name: "INY", operation: cpu.INY, addrmode: cpu.IMP, cycles: 2 },
      { name: "CMP", operation: cpu.CMP, addrmode: cpu.IMM, cycles: 2 },
      { name: "DEX", operation: cpu.DEX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "CPY", operation: cpu.CPY, addrmode: cpu.ABS, cycles: 4 },
      { name: "CMP", operation: cpu.CMP, addrmode: cpu.ABS, cycles: 4 },
      { name: "DEC", operation: cpu.DEC, addrmode: cpu.ABS, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },

      { name: "BNE", operation: cpu.BNE, addrmode: cpu.REL, cycles: 2 },
      { name: "CMP", operation: cpu.CMP, addrmode: cpu.IZY, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "CMP", operation: cpu.CMP, addrmode: cpu.ZPX, cycles: 4 },
      { name: "DEC", operation: cpu.DEC, addrmode: cpu.ZPX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },
      { name: "CLD", operation: cpu.CLD, addrmode: cpu.IMP, cycles: 2 },
      { name: "CMP", operation: cpu.CMP, addrmode: cpu.ABY, cycles: 4 },
      { name: "NOP", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "CMP", operation: cpu.CMP, addrmode: cpu.ABX, cycles: 4 },
      { name: "DEC", operation: cpu.DEC, addrmode: cpu.ABX, cycles: 7 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },

      { name: "CPX", operation: cpu.CPX, addrmode: cpu.IMM, cycles: 2 },
      { name: "SBC", operation: cpu.SBC, addrmode: cpu.IZX, cycles: 6 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "CPX", operation: cpu.CPX, addrmode: cpu.ZP0, cycles: 3 },
      { name: "SBC", operation: cpu.SBC, addrmode: cpu.ZP0, cycles: 3 },
      { name: "INC", operation: cpu.INC, addrmode: cpu.ZP0, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 5 },
      { name: "INX", operation: cpu.INX, addrmode: cpu.IMP, cycles: 2 },
      { name: "SBC", operation: cpu.SBC, addrmode: cpu.IMM, cycles: 2 },
      { name: "NOP", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.SBC, addrmode: cpu.IMP, cycles: 2 },
      { name: "CPX", operation: cpu.CPX, addrmode: cpu.ABS, cycles: 4 },
      { name: "SBC", operation: cpu.SBC, addrmode: cpu.ABS, cycles: 4 },
      { name: "INC", operation: cpu.INC, addrmode: cpu.ABS, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },

      { name: "BEQ", operation: cpu.BEQ, addrmode: cpu.REL, cycles: 2 },
      { name: "SBC", operation: cpu.SBC, addrmode: cpu.IZY, cycles: 5 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 8 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "SBC", operation: cpu.SBC, addrmode: cpu.ZPX, cycles: 4 },
      { name: "INC", operation: cpu.INC, addrmode: cpu.ZPX, cycles: 6 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 6 },
      { name: "SED", operation: cpu.SED, addrmode: cpu.IMP, cycles: 2 },
      { name: "SBC", operation: cpu.SBC, addrmode: cpu.ABY, cycles: 4 },
      { name: "NOP", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 2 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },
      { name: "???", operation: cpu.NOP, addrmode: cpu.IMP, cycles: 4 },
      { name: "SBC", operation: cpu.SBC, addrmode: cpu.ABX, cycles: 4 },
      { name: "INC", operation: cpu.INC, addrmode: cpu.ABX, cycles: 7 },
      { name: "???", operation: cpu.XXX, addrmode: cpu.IMP, cycles: 7 },
    ];
  }

  public getLookUp() {
    return this.lookup;
  }
}
